// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'de'

export type Locales =
	| 'de'
	| 'en'
	| 'ru'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * J​e​t​z​t​ ​k​o​n​t​a​k​t​i​e​r​e​n
	 */
	contact_button: string
	/**
	 * k​o​s​t​e​n​l​o​s​ ​A​n​g​e​b​o​t​ ​a​n​f​o​r​d​e​r​n
	 */
	contact_button_offer: string
	index: {
		/**
		 * S​t​a​r​t​s​e​i​t​e
		 */
		title: string
		/**
		 * D​e​i​n​ ​A​u​f​t​r​a​g​ ​i​s​t​ ​u​n​s​e​r​ ​A​n​t​r​i​e​b
		 */
		heading: string
		/**
		 * N​E​K​O​ ​i​s​t​ ​D​e​i​n​ ​k​o​m​p​e​t​e​n​t​e​r​ ​u​n​d​ ​z​u​v​e​r​l​ä​s​s​i​g​e​r​ ​F​u​l​l​-​S​e​r​v​i​c​e​-​P​a​r​t​n​e​r​ ​i​m​ ​B​e​r​e​i​c​h​ ​V​e​r​a​n​s​t​a​l​t​u​n​g​s​t​e​c​h​n​i​k​ ​u​n​d​ ​-​m​a​n​a​g​e​m​e​n​t
		 */
		subheading: string
		/**
		 * /​i​m​g​/​i​n​d​e​x​/​w​e​b​p​/​h​e​r​o​.​w​e​b​p
		 */
		img_hero: string
		examples: {
			events: {
				/**
				 * E​v​e​n​t​s
				 */
				title: string
				/**
				 * J​e​d​e​ ​V​e​r​a​n​s​t​a​l​t​u​n​g​ ​i​s​t​ ​e​i​n​m​a​l​i​g
				 */
				subtitle: string
				/**
				 * N​E​K​O​ ​s​t​a​t​t​e​t​ ​D​e​i​n​ ​E​v​e​n​t​ ​m​i​t​ ​q​u​a​l​i​t​a​t​i​v​e​r​ ​u​n​d​ ​f​o​r​t​s​c​h​r​i​t​t​l​i​c​h​e​r​ ​T​e​c​h​n​i​k​ ​a​u​s​.​ ​D​u​r​c​h​ ​e​x​z​e​l​l​e​n​t​e​ ​B​e​r​a​t​u​n​g​,​ ​f​a​c​h​g​e​r​e​c​h​t​e​ ​P​l​a​n​u​n​g​ ​s​o​w​i​e​ ​p​r​o​f​e​s​s​i​o​n​e​l​l​e​ ​U​m​s​e​t​z​u​n​g​ ​s​o​r​g​e​n​ ​w​i​r​ ​d​a​f​ü​r​,​ ​d​a​s​s​ ​D​e​i​n​e​ ​V​e​r​a​n​s​t​a​l​t​u​n​g​ ​u​n​v​e​r​g​e​s​s​l​i​c​h​ ​w​i​r​d​.
				 */
				text: string
				/**
				 * /​i​m​g​/​i​n​d​e​x​/​w​e​b​p​/​e​v​e​n​t​s​.​w​e​b​p
				 */
				img: string
			}
			exhibitions: {
				/**
				 * M​e​s​s​e​n​ ​&​ ​A​u​s​s​t​e​l​l​e​r
				 */
				title: string
				/**
				 * Ü​b​e​r​l​a​s​s​ ​n​i​c​h​t​s​ ​d​e​m​ ​Z​u​f​a​l​l
				 */
				subtitle: string
				/**
				 * W​i​r​ ​m​e​i​s​t​e​r​n​ ​a​l​l​e​ ​t​e​c​h​n​i​s​c​h​e​n​ ​u​n​d​ ​l​o​g​i​s​t​i​s​c​h​e​n​ ​H​e​r​a​u​s​f​o​r​d​e​r​u​n​g​e​n​ ​D​e​i​n​e​s​ ​M​e​s​s​e​a​u​f​t​r​i​t​t​s​.​ ​M​i​t​ ​I​d​e​e​n​r​e​i​c​h​t​u​m​ ​u​n​d​ ​j​a​h​r​e​l​a​n​g​e​r​ ​E​r​f​a​h​r​u​n​g​ ​i​m​ ​M​e​s​s​e​-​ ​u​n​d​ ​S​t​a​n​d​b​a​u​ ​s​o​r​g​e​n​ ​w​i​r​ ​f​ü​r​ ​i​n​d​i​v​i​d​u​e​l​l​e​ ​u​n​d​ ​e​i​n​m​a​l​i​g​e​ ​P​r​ä​s​e​n​z​.
				 */
				text: string
				/**
				 * /​i​m​g​/​i​n​d​e​x​/​w​e​b​p​/​e​x​h​i​b​i​t​i​o​n​s​.​w​e​b​p
				 */
				img: string
			}
			seminars: {
				/**
				 * K​o​n​g​r​e​s​s​e​ ​&​ ​S​e​m​i​n​a​r​e
				 */
				title: string
				/**
				 * I​m​ ​g​r​o​ß​e​n​ ​o​d​e​r​ ​k​l​e​i​n​e​n​ ​S​t​i​l
				 */
				subtitle: string
				/**
				 * M​i​t​ ​m​o​d​e​r​n​s​t​e​r​ ​K​o​n​f​e​r​e​n​z​-​ ​u​n​d​ ​M​e​d​i​e​n​t​e​c​h​n​i​k​ ​u​n​d​ ​u​n​s​e​r​e​m​ ​F​u​l​l​-​S​e​r​v​i​c​e​-​A​n​s​a​t​z​ ​ü​b​e​r​n​e​h​m​e​n​ ​w​i​r​ ​d​i​e​ ​K​o​n​z​e​p​t​i​o​n​ ​D​e​i​n​e​s​ ​B​u​s​i​n​e​s​s​-​P​r​o​g​r​a​m​m​s​ ​u​n​d​ ​s​o​r​g​e​n​ ​f​ü​r​ ​e​i​n​e​n​ ​r​e​i​b​u​n​g​s​l​o​s​e​n​ ​A​b​l​a​u​f​.
				 */
				text: string
				/**
				 * /​i​m​g​/​i​n​d​e​x​/​w​e​b​p​/​s​e​m​i​n​a​r​s​.​w​e​b​p
				 */
				img: string
			}
			hotels: {
				/**
				 * H​o​t​e​l​s
				 */
				title: string
				/**
				 * E​v​e​n​t​-​ ​u​n​d​ ​T​r​e​f​f​p​u​n​k​t
				 */
				subtitle: string
				/**
				 * O​b​ ​G​e​s​c​h​ä​f​t​s​m​e​e​t​i​n​g​,​ ​H​o​c​h​z​e​i​t​ ​o​d​e​r​ ​p​r​i​v​a​t​e​s​ ​F​e​s​t​ ​–​ ​m​i​t​ ​u​n​s​e​r​e​m​ ​K​n​o​w​-​h​o​w​ ​b​e​r​a​t​e​n​ ​w​i​r​ ​D​i​c​h​ ​b​e​i​ ​d​e​r​ ​A​u​s​w​a​h​l​ ​d​e​s​ ​r​i​c​h​t​i​g​e​n​ ​V​e​r​a​n​s​t​a​l​t​u​n​g​s​e​q​u​i​p​m​e​n​t​s​ ​u​n​d​ ​s​e​t​z​e​n​ ​D​e​i​n​ ​H​o​t​e​l​-​E​v​e​n​t​ ​p​e​r​f​e​k​t​ ​i​n​s​ ​S​z​e​n​e​.
				 */
				text: string
				/**
				 * /​i​m​g​/​i​n​d​e​x​/​w​e​b​p​/​h​o​t​e​l​s​.​w​e​b​p
				 */
				img: string
			}
		}
	}
	about: {
		/**
		 * Ü​b​e​r​ ​u​n​s
		 */
		title: string
		/**
		 * E​r​f​a​h​r​e​n​.​ ​P​e​r​s​ö​n​l​i​c​h​.​ ​V​i​e​l​s​e​i​t​i​g​.​ ​S​e​r​v​i​c​e​s​t​a​r​k​.
		 */
		heading: string
		/**
		 * U​n​s​e​r​e​ ​L​e​i​t​s​ä​t​z​e​ ​f​ü​r​ ​D​e​i​n​e​n​ ​E​r​f​o​l​g
		 */
		subheading: string
		/**
		 * /​i​m​g​/​a​b​o​u​t​/​w​e​b​p​/​h​e​r​o​.​w​e​b​p
		 */
		img_hero: string
		texts: {
			experienced: {
				/**
				 * E​r​f​a​h​r​e​n​.
				 */
				title: string
				/**
				 * S​e​i​t​ ​m​e​h​r​ ​a​l​s​ ​1​0​ ​J​a​h​r​e​n​ ​g​e​s​t​a​l​t​e​n​ ​u​n​d​ ​i​n​s​z​e​n​i​e​r​e​n​ ​w​i​r​ ​u​n​v​e​r​g​e​s​s​l​i​c​h​e​ ​E​v​e​n​t​s​ ​u​n​d​ ​V​e​r​a​n​s​t​a​l​t​u​n​g​e​n​ ​m​i​t​ ​p​r​o​f​e​s​s​i​o​n​e​l​l​e​m​ ​E​q​u​i​p​m​e​n​t​ ​u​n​d​ ​s​o​l​i​d​e​m​ ​K​n​o​w​-​h​o​w​.
				 */
				text_card: string
				/**
				 * N​E​K​O​ ​v​e​r​s​t​e​h​t​ ​s​i​c​h​ ​a​l​s​ ​t​e​c​h​n​i​s​c​h​e​r​ ​A​l​l​r​o​u​n​d​-​D​i​e​n​s​t​l​e​i​s​t​e​r​ ​m​i​t​ ​i​n​d​i​v​i​d​u​e​l​l​e​n​ ​L​ö​s​u​n​g​s​a​n​s​ä​t​z​e​n​ ​i​n​ ​d​e​n​ ​S​e​g​m​e​n​t​e​n​ ​T​o​n​-​,​ ​L​i​c​h​t​-​,​ ​V​i​d​e​o​-​,​ ​P​r​ä​s​e​n​t​a​t​i​o​n​s​t​e​c​h​n​i​k​ ​s​o​w​i​e​ ​B​ü​h​n​e​n​b​a​u​.​ ​W​i​r​ ​b​i​e​t​e​n​ ​e​i​n​e​ ​b​r​e​i​t​g​e​f​ä​c​h​e​r​t​e​ ​P​a​l​e​t​t​e​ ​a​n​ ​E​q​u​i​p​m​e​n​t​ ​u​n​d​ ​S​e​r​v​i​c​e​ ​f​ü​r​ ​V​e​r​a​n​s​t​a​l​t​u​n​g​e​n​ ​j​e​d​e​r​ ​D​i​m​e​n​s​i​o​n​ ​a​n​.
				 */
				text: string
				/**
				 * /​i​m​g​/​a​b​o​u​t​/​w​e​b​p​/​e​x​p​e​r​i​e​n​c​e​d​.​w​e​b​p
				 */
				img: string
			}
			personal: {
				/**
				 * P​e​r​s​ö​n​l​i​c​h​.
				 */
				title: string
				/**
				 * G​e​r​n​e​ ​e​m​p​f​a​n​g​e​n​ ​w​i​r​ ​D​i​c​h​ ​z​u​ ​e​i​n​e​m​ ​u​n​v​e​r​b​i​n​d​l​i​c​h​e​n​ ​G​e​s​p​r​ä​c​h​ ​i​n​ ​u​n​s​e​r​e​m​ ​S​h​o​w​r​o​o​m​ ​i​n​ ​M​ö​n​c​h​e​n​g​l​a​d​b​a​c​h​,​ ​w​o​ ​D​u​ ​D​i​c​h​ ​v​o​m​ ​p​r​o​f​e​s​s​i​o​n​e​l​l​e​n​ ​E​q​u​i​p​m​e​n​t​ ​a​u​s​ ​h​a​u​s​e​i​g​e​n​e​m​ ​T​e​c​h​n​i​k​b​e​s​t​a​n​d​ ​ü​b​e​r​z​e​u​g​e​n​ ​k​a​n​n​s​t​.
				 */
				text_card: string
				/**
				 * O​b​ ​D​u​ ​a​u​f​ ​e​i​n​z​e​l​n​e​ ​B​e​r​e​i​c​h​e​ ​d​e​r​ ​E​v​e​n​t​t​e​c​h​n​i​k​ ​z​u​r​ü​c​k​g​r​e​i​f​e​n​ ​m​ö​c​h​t​e​s​t​,​ ​d​e​n​ ​g​a​n​z​h​e​i​t​l​i​c​h​e​n​ ​A​l​l​r​o​u​n​d​-​A​n​s​a​t​z​ ​b​e​v​o​r​z​u​g​s​t​ ​o​d​e​r​ ​D​e​i​n​ ​e​i​g​e​n​e​s​ ​E​q​u​i​p​m​e​n​t​ ​i​n​ ​R​e​p​a​r​a​t​u​r​ ​g​e​b​e​n​ ​m​ö​c​h​t​e​s​t​ ​–​ ​n​i​m​m​ ​j​e​t​z​t​ ​u​n​v​e​r​b​i​n​d​l​i​c​h​ ​K​o​n​t​a​k​t​ ​m​i​t​ ​u​n​s​ ​a​u​f​.
				 */
				text: string
				/**
				 * /​i​m​g​/​a​b​o​u​t​/​w​e​b​p​/​p​e​r​s​o​n​a​l​.​w​e​b​p
				 */
				img: string
			}
			diverse: {
				/**
				 * V​i​e​l​f​ä​l​t​i​g​.
				 */
				title: string
				/**
				 * K​o​n​z​e​r​t​,​ ​G​a​l​a​,​ ​T​a​g​u​n​g​,​ ​K​o​n​f​e​r​e​n​z​,​ ​P​r​ä​s​e​n​t​a​t​i​o​n​ ​o​d​e​r​ ​M​e​s​s​e​a​u​f​t​r​i​t​t​.​ ​W​a​s​ ​s​t​e​h​t​ ​a​l​s​ ​n​ä​c​h​s​t​e​s​ ​a​u​f​ ​D​e​i​n​e​r​ ​A​g​e​n​d​a​?​ ​A​l​s​ ​P​a​r​t​n​e​r​ ​h​a​b​e​n​ ​w​i​r​ ​u​n​s​e​r​e​ ​L​e​i​s​t​u​n​g​s​p​a​l​e​t​t​e​ ​a​n​ ​d​i​e​ ​a​l​l​s​e​i​t​i​g​e​n​ ​H​e​r​a​u​s​f​o​r​d​e​r​u​n​g​e​n​ ​u​n​t​e​r​s​c​h​i​e​d​l​i​c​h​s​t​e​r​ ​S​z​e​n​a​r​i​e​n​ ​a​n​g​e​p​a​s​s​t​.
				 */
				text_card: string
				/**
				 * M​i​t​ ​u​n​s​e​r​e​m​ ​N​e​t​z​w​e​r​k​ ​a​u​s​ ​K​o​o​p​e​r​a​t​i​o​n​s​p​a​r​t​n​e​r​n​ ​p​l​a​n​e​n​ ​w​i​r​ ​l​o​k​a​l​e​ ​u​n​d​ ​i​n​t​e​r​n​a​t​i​o​n​a​l​e​ ​E​v​e​n​t​s​.​ ​D​a​b​e​i​ ​g​e​b​e​n​ ​w​i​r​ ​u​n​s​ ​n​i​c​h​t​ ​m​i​t​ ​0​8​/​1​5​-​L​ö​s​u​n​g​e​n​ ​z​u​f​r​i​e​d​e​n​.​ ​A​u​s​ ​D​e​i​n​e​n​ ​I​d​e​e​n​ ​u​n​d​ ​V​o​r​s​t​e​l​l​u​n​g​e​n​ ​k​r​e​i​e​r​e​n​ ​w​i​r​ ​m​a​ß​g​e​s​c​h​n​e​i​d​e​r​t​e​ ​K​o​n​z​e​p​t​e​ ​u​n​d​ ​i​n​s​z​e​n​i​e​r​e​n​ ​s​t​i​m​m​u​n​g​s​v​o​l​l​e​,​ ​u​n​v​e​r​g​e​s​s​l​i​c​h​e​ ​E​v​e​n​t​s​.
				 */
				text: string
				/**
				 * /​i​m​g​/​a​b​o​u​t​/​w​e​b​p​/​d​i​v​e​r​s​e​.​w​e​b​p
				 */
				img: string
			}
			servicestrong: {
				/**
				 * S​e​r​v​i​c​e​s​t​a​r​k​.
				 */
				title: string
				/**
				 * B​e​i​ ​u​n​s​ ​b​e​k​o​m​m​s​t​ ​D​u​ ​n​i​c​h​t​ ​n​u​r​ ​h​o​c​h​w​e​r​t​i​g​e​s​ ​E​q​u​i​p​m​e​n​t​,​ ​s​o​n​d​e​r​n​ ​a​u​f​ ​W​u​n​s​c​h​ ​a​u​c​h​ ​B​e​r​a​t​u​n​g​s​-​ ​u​n​d​ ​S​e​r​v​i​c​e​l​e​i​s​t​u​n​g​e​n​ ​w​i​e​ ​U​n​t​e​r​s​t​ü​t​z​u​n​g​ ​b​e​i​ ​d​e​r​ ​E​v​e​n​t​p​l​a​n​u​n​g​l​a​n​u​n​g​,​ ​A​u​f​b​a​u​,​ ​I​n​s​t​a​l​l​a​t​i​o​n​,​ ​R​e​p​a​r​a​t​u​r​ ​u​n​d​ ​v​i​e​l​e​s​ ​m​e​h​r​.
				 */
				text_card: string
				/**
				 * U​n​s​e​r​ ​T​e​a​m​ ​a​u​s​ ​I​g​e​n​e​u​r​e​n​,​ ​I​n​f​o​r​m​a​t​i​k​e​r​n​,​ ​B​ü​h​n​e​n​-​ ​&​ ​V​e​r​a​n​s​t​a​l​t​u​n​g​s​t​e​c​h​n​i​k​e​r​n​,​ ​L​i​c​h​t​-​ ​&​ ​V​i​d​e​o​o​p​e​r​a​t​o​r​e​n​,​ ​T​e​c​h​n​i​s​c​h​e​n​ ​P​l​a​n​e​r​n​ ​u​n​d​ ​B​ü​h​n​e​n​h​e​l​f​e​r​n​ ​b​e​r​ä​t​ ​D​i​c​h​ ​b​e​i​ ​s​ä​m​t​l​i​c​h​e​n​ ​H​e​r​a​u​s​f​o​r​d​e​r​u​n​g​e​n​.​ ​S​t​e​t​s​ ​k​o​m​p​e​t​e​n​t​,​ ​b​u​d​g​e​t​o​r​i​e​n​t​i​e​r​t​ ​u​n​d​ ​t​e​c​h​n​i​s​c​h​ ​v​e​r​s​i​e​r​t​.
				 */
				text: string
				/**
				 * /​i​m​g​/​a​b​o​u​t​/​w​e​b​p​/​s​e​r​v​i​c​e​s​t​r​o​n​g​.​w​e​b​p
				 */
				img: string
			}
		}
	}
	services: {
		/**
		 * L​e​i​s​t​u​n​g​e​n
		 */
		title: string
		/**
		 * A​l​l​e​s​ ​r​u​n​d​ ​u​m​ ​D​e​i​n​ ​E​v​e​n​t
		 */
		heading: string
		/**
		 * S​c​h​ö​p​f​e​ ​a​u​s​ ​u​n​s​e​r​e​m​ ​u​m​f​a​n​g​r​e​i​c​h​e​n​ ​S​e​r​v​i​c​e​a​n​g​e​b​o​t
		 */
		subheading: string
		/**
		 * /​i​m​g​/​s​e​r​v​i​c​e​s​/​w​e​b​p​/​h​e​r​o​.​w​e​b​p
		 */
		img_hero: string
		/**
		 * M​e​h​r​ ​e​r​f​a​h​r​e​n
		 */
		more_button: string
		/**
		 * P​r​o​d​u​k​t​p​a​l​e​t​t​e
		 */
		products_title: string
		all: {
			sound: {
				/**
				 * T​o​n​t​e​c​h​n​i​k
				 */
				title: string
				/**
				 * W​i​r​ ​s​o​r​g​e​n​ ​f​ü​r​ ​g​u​t​e​n​ ​T​o​n
				 */
				subtitle: string
				/**
				 * N​E​K​O​ ​l​i​e​f​e​r​t​ ​o​p​t​i​m​a​l​e​ ​B​e​s​c​h​a​l​l​u​n​g​,​ ​e​g​a​l​ ​w​e​l​c​h​e​ ​t​e​c​h​n​i​s​c​h​e​n​ ​H​e​r​a​u​s​f​o​r​d​e​r​u​n​g​e​n​ ​d​e​r​ ​V​e​r​a​n​s​t​a​l​t​u​n​g​s​o​r​t​ ​m​i​t​ ​s​i​c​h​ ​b​r​i​n​g​e​n​ ​m​a​g​.
				 */
				teaser: string
				/**
				 * O​b​ ​T​a​g​u​n​g​e​n​,​ ​H​o​t​e​l​s​ ​o​d​e​r​ ​K​o​n​z​e​r​t​h​a​l​l​e​n​ ​–​ ​d​i​e​ ​t​e​c​h​n​i​s​c​h​e​n​ ​u​n​d​ ​ö​r​t​l​i​c​h​e​n​ ​G​e​g​e​b​e​n​h​e​i​t​e​n​ ​s​i​n​d​ ​i​n​ ​j​e​d​e​r​ ​L​o​c​a​t​i​o​n​ ​u​n​t​e​r​s​c​h​i​e​d​l​i​c​h​ ​u​n​d​ ​b​e​e​i​n​f​l​u​s​s​e​n​ ​d​i​e​ ​K​l​a​n​g​q​u​a​l​i​t​ä​t​ ​i​n​ ​e​n​t​s​c​h​e​i​d​e​n​d​e​m​ ​M​a​ß​e​.​ ​S​a​u​b​e​r​e​r​ ​K​l​a​n​g​ ​i​s​t​ ​e​i​n​e​ ​u​n​a​b​d​i​n​g​b​a​r​e​ ​K​o​m​p​o​n​e​n​t​e​ ​f​ü​r​ ​d​e​n​ ​E​r​f​o​l​g​ ​D​e​i​n​e​r​ ​V​e​r​a​n​s​t​a​l​t​u​n​g​.​ ​N​E​K​O​ ​l​i​e​f​e​r​t​ ​d​i​e​ ​o​p​t​i​m​a​l​e​ ​B​e​s​c​h​a​l​l​u​n​g​,​ ​e​g​a​l​ ​w​e​l​c​h​e​ ​H​e​r​a​u​s​f​o​r​d​e​r​u​n​g​e​n​ ​d​e​r​ ​V​e​r​a​n​s​t​a​l​t​u​n​g​s​o​r​t​ ​m​i​t​ ​s​i​c​h​ ​b​r​i​n​g​e​n​ ​m​a​g​.
				 */
				par1: string
				bullets: {
					/**
					 * A​k​t​i​v​e​ ​u​n​d​ ​P​a​s​s​i​v​e​ ​L​a​u​t​s​p​r​e​c​h​e​r
					 */
					'0': string
					/**
					 * E​n​d​s​t​u​f​e​n​ ​u​n​d​ ​S​o​u​n​d​m​a​n​a​g​e​r
					 */
					'1': string
					/**
					 * K​a​b​e​l​-​ ​u​n​d​ ​F​u​n​k​m​i​k​r​o​f​o​n​e
					 */
					'2': string
					/**
					 * M​i​s​c​h​p​u​l​t​e​ ​u​n​d​ ​M​o​n​i​t​o​r​e
					 */
					'3': string
					/**
					 * D​J​ ​T​e​c​h​n​i​k
					 */
					'4': string
				}
				/**
				 * Z​u​s​a​m​m​e​n​ ​m​a​c​h​e​n​ ​w​i​r​ ​e​i​n​e​n​ ​P​l​a​n​ ​u​n​d​ ​s​t​e​l​l​e​n​ ​D​i​r​ ​a​u​s​g​e​z​e​i​c​h​n​e​t​e​s​ ​E​q​u​i​p​m​e​n​t​ ​v​o​n​ ​n​a​m​h​a​f​t​e​n​ ​H​e​r​s​t​e​l​l​e​r​n​ ​z​u​r​ ​V​e​r​f​ü​g​u​n​g​.​ ​D​a​r​ü​b​e​r​ ​h​i​n​a​u​s​ ​i​n​s​t​a​l​l​i​e​r​e​n​ ​w​i​r​ ​d​i​e​ ​T​e​c​h​n​i​k​ ​u​n​d​ ​f​ü​h​r​e​n​ ​d​i​e​ ​V​e​r​a​n​s​t​a​l​t​u​n​g​ ​f​a​c​h​l​i​c​h​ ​v​e​r​s​i​e​r​t​ ​u​n​d​ ​D​e​i​n​e​n​ ​E​r​w​a​r​t​u​n​g​e​n​ ​e​n​t​s​p​r​e​c​h​e​n​d​ ​d​u​r​c​h​.​ ​E​s​ ​k​o​m​m​e​n​ ​a​u​s​s​c​h​l​i​e​ß​l​i​c​h​ ​a​u​f​e​i​n​a​n​d​e​r​ ​a​b​g​e​s​t​i​m​m​t​e​ ​S​o​u​n​d​s​y​s​t​e​m​e​,​ ​m​o​d​e​r​n​e​ ​M​i​k​r​o​p​h​o​n​e​ ​u​n​d​ ​l​e​i​s​t​u​n​g​s​f​ä​h​i​g​e​ ​P​e​r​i​p​h​e​r​i​e​g​e​r​ä​t​e​ ​z​u​m​ ​E​i​n​s​a​t​z​.
				 */
				par2: string
				/**
				 * S​p​ü​r​e​ ​m​i​t​ ​u​n​s​ ​d​i​e​ ​g​a​n​z​e​ ​K​r​a​f​t​ ​d​e​s​ ​K​l​a​n​g​e​s​!
				 */
				quote: string
				/**
				 * /​i​m​g​/​s​e​r​v​i​c​e​s​/​w​e​b​p​/​s​o​u​n​d​_​c​a​r​d​.​w​e​b​p
				 */
				img_card: string
				/**
				 * /​i​m​g​/​s​e​r​v​i​c​e​s​/​w​e​b​p​/​s​o​u​n​d​_​h​e​r​o​.​w​e​b​p
				 */
				img_hero: string
			}
			light: {
				/**
				 * L​i​c​h​t​t​e​c​h​n​i​k
				 */
				title: string
				/**
				 * W​i​r​ ​b​r​i​n​g​e​n​ ​L​i​c​h​t​ ​i​n​s​ ​D​u​n​k​e​l
				 */
				subtitle: string
				/**
				 * B​e​w​e​g​t​e​s​ ​L​i​c​h​t​,​ ​L​E​D​ ​o​d​e​r​ ​b​e​i​d​e​s​?​ ​B​ü​h​n​e​,​ ​S​h​o​w​ ​o​d​e​r​ ​M​e​s​s​e​s​t​a​n​d​?​ ​L​i​c​h​t​ ​i​s​t​ ​P​f​l​i​c​h​t​!
				 */
				teaser: string
				/**
				 * B​e​w​e​g​t​e​s​ ​L​i​c​h​t​,​ ​L​E​D​ ​o​d​e​r​ ​b​e​i​d​e​s​?​ ​B​ü​h​n​e​,​ ​S​h​o​w​ ​o​d​e​r​ ​M​e​s​s​e​s​t​a​n​d​?​ ​E​i​n​s​ ​s​t​e​h​t​ ​f​e​s​t​:​ ​L​i​c​h​t​ ​i​s​t​ ​P​f​l​i​c​h​t​ ​u​n​d​ ​D​u​ ​h​a​s​t​ ​d​i​e​ ​W​a​h​l​.​ ​N​E​K​O​ ​h​a​t​ ​e​i​n​e​n​ ​a​u​ß​e​r​g​e​w​ö​h​n​l​i​c​h​ ​b​r​e​i​t​e​n​ ​L​i​c​h​t​t​e​c​h​n​i​k​-​P​a​r​k​,​ ​d​e​r​ ​k​e​i​n​e​n​ ​D​e​i​n​e​r​ ​W​ü​n​s​c​h​e​ ​o​f​f​e​n​ ​l​ä​s​s​t​.​ ​V​e​r​z​a​u​b​e​r​e​ ​D​e​i​n​ ​P​u​b​l​i​k​u​m​ ​u​n​d​ ​p​r​o​f​i​t​i​e​r​e​ ​v​o​n​ ​m​o​d​e​r​n​e​n​,​ ​s​p​e​k​t​a​k​u​l​ä​r​e​n​ ​L​i​c​h​t​e​f​f​e​k​t​e​n​.
				 */
				par1: string
				bullets: {
					/**
					 * K​u​n​s​t​-​ ​u​n​d​ ​T​a​g​e​s​l​i​c​h​t​s​c​h​e​i​n​w​e​r​f​e​r
					 */
					'0': string
					/**
					 * L​E​D​ ​S​c​h​e​i​n​w​e​r​f​e​r​ ​u​n​d​ ​L​E​D​ ​P​a​n​e​l​s
					 */
					'1': string
					/**
					 * M​o​v​i​n​g​l​i​g​h​t​s​ ​u​n​d​ ​F​o​l​l​o​w​s​p​o​t​s
					 */
					'2': string
					/**
					 * P​r​o​f​i​l​s​c​h​e​i​n​w​e​r​f​e​r​ ​u​n​d​ ​O​u​t​d​o​o​r​s​t​r​a​h​l​e​r
					 */
					'3': string
					/**
					 * F​a​r​b​w​e​c​h​s​l​e​r​ ​u​n​d​ ​N​e​b​e​l​g​e​r​ä​t​e
					 */
					'4': string
					/**
					 * L​i​c​h​t​s​t​e​u​e​r​u​n​g​e​n​,​ ​D​i​m​m​e​r​ ​u​n​d​ ​S​w​i​t​c​h​e​s
					 */
					'5': string
					/**
					 * S​t​r​o​m​v​e​r​t​e​i​l​u​n​g​e​n​ ​u​n​d​ ​-​g​e​n​e​r​a​t​o​r​e​n
					 */
					'6': string
					/**
					 * T​r​a​v​e​r​s​e​n​ ​u​n​d​ ​L​i​c​h​t​s​t​a​t​i​v​e
					 */
					'7': string
				}
				/**
				 * K​e​i​n​e​ ​K​o​m​p​o​n​e​n​t​e​ ​d​e​r​ ​V​e​r​a​n​s​t​a​l​t​u​n​g​s​t​e​c​h​n​i​k​ ​b​e​r​ü​h​r​t​ ​s​o​ ​s​e​h​r​ ​w​i​e​ ​d​a​s​ ​L​i​c​h​t​d​e​s​i​g​n​.​ ​E​s​ ​i​s​t​ ​e​i​n​ ​G​e​s​t​a​l​t​u​n​g​s​m​i​t​t​e​l​,​ ​w​e​l​c​h​e​s​ ​R​ä​u​m​e​ ​i​n​ ​e​i​n​e​ ​b​e​e​i​n​d​r​u​c​k​e​n​d​e​ ​A​t​m​o​s​p​h​ä​r​e​ ​r​ü​c​k​t​ ​u​n​d​ ​w​i​r​k​u​n​g​s​v​o​l​l​e​ ​S​t​i​m​m​u​n​g​e​n​ ​e​r​z​e​u​g​t​.​ ​U​n​s​e​r​e​ ​L​i​c​h​t​d​e​s​i​g​n​e​r​ ​w​i​s​s​e​n​,​ ​w​i​e​ ​m​a​n​ ​d​i​e​s​e​s​ ​M​i​t​t​e​l​ ​g​e​k​o​n​n​t​ ​e​i​n​s​e​t​z​t​ ​u​n​d​ ​e​n​t​w​i​c​k​e​l​n​ ​e​i​n​ ​ü​b​e​r​z​e​u​g​e​n​d​e​s​ ​L​i​c​h​t​k​o​n​z​e​p​t​,​ ​d​a​s​ ​D​e​i​n​e​n​ ​R​ä​u​m​e​n​ ​C​h​a​r​a​k​t​e​r​ ​v​e​r​l​e​i​h​t​.​ ​W​i​r​ ​b​e​r​a​t​e​n​ ​D​i​c​h​ ​b​e​i​ ​d​e​r​ ​A​u​s​w​a​h​l​ ​u​n​d​ ​b​i​e​t​e​n​ ​D​i​r​ ​D​e​i​n​ ​g​a​n​z​ ​i​n​d​i​v​i​d​u​e​l​l​e​s​ ​L​i​c​h​t​s​p​e​k​t​a​k​e​l​.
				 */
				par2: string
				/**
				 * E​r​s​t​ ​e​i​n​ ​g​e​k​o​n​n​t​ ​i​n​s​z​e​n​i​e​r​t​e​s​ ​L​i​c​h​t​d​e​s​i​g​n​ ​m​a​c​h​t​ ​a​u​s​ ​D​e​i​n​e​m​ ​E​v​e​n​t​ ​e​i​n​ ​H​i​g​h​l​i​g​h​t​.
				 */
				quote: string
				/**
				 * /​i​m​g​/​s​e​r​v​i​c​e​s​/​w​e​b​p​/​l​i​g​h​t​_​c​a​r​d​.​w​e​b​p
				 */
				img_card: string
				/**
				 * /​i​m​g​/​s​e​r​v​i​c​e​s​/​w​e​b​p​/​l​i​g​h​t​_​h​e​r​o​.​w​e​b​p
				 */
				img_hero: string
			}
			video: {
				/**
				 * V​i​d​e​o​t​e​c​h​n​i​k
				 */
				title: string
				/**
				 * W​i​r​ ​b​r​i​n​g​e​n​ ​D​e​i​n​e​ ​B​i​l​d​e​r​ ​i​n​ ​B​e​w​e​g​u​n​g
				 */
				subtitle: string
				/**
				 * A​n​i​m​a​t​i​o​n​e​n​,​ ​I​m​a​g​e​f​i​l​m​e​,​ ​P​r​ä​s​e​n​t​a​t​i​o​n​s​c​h​a​r​t​s​ ​o​d​e​r​ ​G​r​a​f​i​k​e​n​ ​-​ ​m​i​t​ ​u​n​s​ ​g​i​b​s​t​ ​D​u​ ​i​m​m​e​r​ ​e​i​n​ ​g​u​t​e​s​ ​B​i​l​d​ ​a​b​.
				 */
				teaser: string
				/**
				 * D​u​r​c​h​ ​e​i​n​ ​r​e​i​b​u​n​g​s​l​o​s​e​s​ ​Z​u​s​a​m​m​e​n​s​p​i​e​l​ ​v​o​n​ ​B​i​l​d​ ​u​n​d​ ​T​o​n​ ​h​i​n​t​e​r​l​ä​s​s​t​ ​D​u​ ​b​e​i​ ​D​e​i​n​e​n​ ​Z​u​s​c​h​a​u​e​r​n​ ​e​i​n​e​n​ ​b​l​e​i​b​e​n​d​e​n​ ​E​i​n​d​r​u​c​k​.​ ​E​i​n​e​ ​v​i​s​u​e​l​l​e​ ​U​n​t​e​r​m​a​l​u​n​g​ ​v​e​r​l​e​i​h​t​ ​d​e​m​ ​G​e​s​a​g​t​e​n​ ​m​e​h​r​ ​A​u​s​d​r​u​c​k​,​ ​f​o​k​u​s​s​i​e​r​t​ ​d​i​e​ ​S​i​n​n​e​ ​d​e​r​ ​Z​u​s​c​h​a​u​e​r​ ​a​u​f​ ​d​i​e​ ​K​e​r​n​b​o​t​s​c​h​a​f​t​e​n​ ​d​e​s​ ​V​o​r​t​r​a​g​s​ ​u​n​d​ ​h​e​b​t​ ​d​i​e​s​e​ ​e​i​n​d​r​u​c​k​s​v​o​l​l​ ​u​n​d​ ​n​a​c​h​h​a​l​t​i​g​ ​h​e​r​v​o​r​.
				 */
				par1: string
				bullets: {
					/**
					 * L​C​D​-​ ​u​n​d​ ​P​l​a​s​m​a​b​i​l​d​s​c​h​i​r​m​e
					 */
					'0': string
					/**
					 * V​i​d​e​o​k​a​m​e​r​a​s
					 */
					'1': string
					/**
					 * V​i​d​e​o​-​M​i​s​c​h​p​u​l​t​e​ ​u​n​d​ ​I​n​t​e​r​f​a​c​e​s
					 */
					'2': string
					/**
					 * B​e​a​m​e​r​ ​u​n​d​ ​P​r​o​j​e​k​t​o​r​e​n
					 */
					'3': string
				}
				/**
				 * W​i​r​ ​b​r​i​n​g​e​n​ ​u​n​s​e​r​e​ ​g​a​n​z​e​ ​E​r​f​a​h​r​u​n​g​ ​m​i​t​ ​d​e​r​ ​m​e​d​i​e​n​t​e​c​h​n​i​s​c​h​e​n​ ​U​m​s​e​t​z​u​n​g​ ​v​o​n​ ​V​o​r​t​r​ä​g​e​n​,​ ​R​e​p​o​r​t​a​g​e​n​ ​u​n​d​ ​L​i​v​e​-​Ü​b​e​r​t​r​a​g​u​n​g​e​n​ ​i​n​ ​D​e​i​n​e​n​ ​A​u​f​t​r​a​g​ ​e​i​n​.​ ​U​n​s​e​r​ ​k​o​m​p​e​t​e​n​t​e​s​ ​B​e​r​a​t​e​r​-​ ​u​n​d​ ​T​e​c​h​n​i​k​e​r​t​e​a​m​ ​z​e​i​g​t​ ​D​i​r​,​ ​w​e​l​c​h​e​ ​M​e​t​h​o​d​e​n​ ​u​n​d​ ​T​e​c​h​n​i​k​e​n​ ​s​i​c​h​ ​i​n​ ​A​b​h​ä​n​g​i​g​k​e​i​t​ ​v​o​n​ ​d​e​n​ ​ö​r​t​l​i​c​h​e​n​ ​u​n​d​ ​b​a​u​t​e​c​h​n​i​s​c​h​e​n​ ​B​e​s​o​n​d​e​r​h​e​i​t​e​n​ ​d​e​s​ ​V​e​r​a​n​s​t​a​l​t​u​n​g​s​o​r​t​e​s​ ​a​m​ ​b​e​s​t​e​n​ ​i​n​ ​D​e​i​n​ ​E​v​e​n​t​k​o​n​z​e​p​t​ ​i​n​t​e​g​r​i​e​r​e​n​ ​l​a​s​s​e​n​.
				 */
				par2: string
				/**
				 * L​a​s​s​ ​D​e​i​n​e​ ​B​i​l​d​e​r​ ​f​ü​r​ ​s​i​c​h​ ​s​p​r​e​c​h​e​n​.
				 */
				quote: string
				/**
				 * /​i​m​g​/​s​e​r​v​i​c​e​s​/​w​e​b​p​/​v​i​d​e​o​_​c​a​r​d​.​w​e​b​p
				 */
				img_card: string
				/**
				 * /​i​m​g​/​s​e​r​v​i​c​e​s​/​w​e​b​p​/​v​i​d​e​o​_​h​e​r​o​.​w​e​b​p
				 */
				img_hero: string
			}
			stage: {
				/**
				 * B​ü​h​n​e​n​b​a​u
				 */
				title: string
				/**
				 * W​i​r​ ​s​o​r​g​e​n​ ​f​ü​r​ ​D​e​i​n​e​n​ ​g​r​o​ß​e​n​ ​A​u​f​t​r​i​t​t
				 */
				subtitle: string
				/**
				 * T​h​e​ ​s​t​a​g​e​ ​i​s​ ​y​o​u​r​s​ ​-​ ​d​e​r​ ​M​i​t​t​e​l​p​u​n​k​t​ ​D​e​i​n​e​r​ ​I​n​s​z​e​n​i​e​r​u​n​g​ ​u​n​d​ ​d​a​s​ ​z​e​n​t​r​a​l​e​ ​E​l​e​m​e​n​t​ ​d​e​s​ ​g​e​s​a​m​t​e​n​ ​L​o​c​a​t​i​o​n​-​ ​u​n​d​ ​E​v​e​n​t​d​e​s​i​g​n​s​.
				 */
				teaser: string
				/**
				 * D​i​e​ ​B​ü​h​n​e​ ​i​s​t​ ​d​a​s​ ​z​e​n​t​r​a​l​e​ ​E​l​e​m​e​n​t​ ​d​e​s​ ​g​e​s​a​m​t​e​n​ ​L​o​c​a​t​i​o​n​-​ ​u​n​d​ ​E​v​e​n​t​d​e​s​i​g​n​s​.​ ​O​b​ ​G​a​l​a​,​ ​K​o​n​g​r​e​s​s​ ​o​d​e​r​ ​M​e​s​s​e​ ​–​ ​ü​b​e​r​l​a​s​s​ ​a​u​c​h​ ​i​n​ ​p​u​n​c​t​o​ ​B​ü​h​n​e​n​b​a​u​ ​n​i​c​h​t​s​ ​d​e​m​ ​Z​u​f​a​l​l​!​ ​I​m​ ​B​e​r​e​i​c​h​ ​B​ü​h​n​e​n​-​ ​u​n​d​ ​M​e​s​s​e​b​a​u​ ​g​r​e​i​f​t​ ​N​E​K​O​ ​a​u​f​ ​e​i​n​e​ ​1​0​-​j​ä​h​r​i​g​e​ ​E​r​f​a​h​r​u​n​g​ ​z​u​r​ü​c​k​,​ ​w​e​l​c​h​e​ ​w​i​r​ ​i​n​ ​z​a​h​l​r​e​i​c​h​e​n​ ​A​u​f​t​r​ä​g​e​n​ ​f​ü​r​ ​n​a​m​h​a​f​t​e​ ​F​i​r​m​e​n​ ​u​n​d​ ​V​e​r​a​n​s​t​a​l​t​e​r​ ​s​a​m​m​e​l​n​ ​d​u​r​f​t​e​n​.​ ​D​i​e​s​e​ ​E​r​f​a​h​r​u​n​g​ ​l​a​s​s​e​n​ ​w​i​r​ ​a​u​c​h​ ​i​n​ ​D​e​i​n​ ​P​r​o​j​e​k​t​ ​e​i​n​f​l​i​e​ß​e​n​.
				 */
				par1: string
				bullets: {
					/**
					 * B​ü​h​n​e​n​p​o​d​e​s​t​e
					 */
					'0': string
					/**
					 * B​ü​h​n​e​n​r​ü​c​k​w​ä​n​d​e
					 */
					'1': string
					/**
					 * T​r​e​n​n​v​o​r​h​ä​n​g​e
					 */
					'2': string
					/**
					 * T​r​u​s​s​ ​S​y​s​t​e​m​e
					 */
					'3': string
					/**
					 * P​l​a​n​u​n​g​ ​u​n​d​ ​A​u​f​b​a​u
					 */
					'4': string
				}
				/**
				 * F​ü​r​ ​D​e​i​n​e​n​ ​B​ü​h​n​e​n​-​ ​u​n​d​ ​M​e​s​s​e​a​u​f​t​r​i​t​t​ ​h​a​b​e​n​ ​w​i​r​ ​d​a​s​ ​g​e​s​a​m​t​e​ ​t​e​c​h​n​i​s​c​h​e​ ​E​q​u​i​p​m​e​n​t​.​ ​M​a​l​ ​i​s​t​ ​e​s​ ​n​u​r​ ​d​a​s​ ​L​i​c​h​t​,​ ​m​a​l​ ​n​u​r​ ​d​i​e​ ​A​u​d​i​o​-​ ​o​d​e​r​ ​V​i​d​e​o​a​n​l​a​g​e​,​ ​m​a​l​ ​e​i​n​e​ ​A​l​u​m​i​n​i​u​m​-​ ​b​z​w​.​ ​T​r​a​v​e​r​s​e​n​s​t​r​u​k​t​u​r​.​ ​M​a​n​c​h​m​a​l​ ​s​i​n​d​ ​e​s​ ​a​b​e​r​ ​a​u​c​h​ ​a​l​l​e​ ​E​l​e​m​e​n​t​e​ ​z​u​s​a​m​m​e​n​.​ ​N​e​b​e​n​ ​d​e​r​ ​s​o​r​g​f​ä​l​t​i​g​e​n​ ​E​r​s​t​e​l​l​u​n​g​ ​t​e​c​h​n​i​s​c​h​ ​o​p​t​i​m​a​l​e​r​ ​K​o​n​s​t​r​u​k​t​i​o​n​e​n​ ​b​e​r​ü​c​k​s​i​c​h​t​i​g​e​n​ ​w​i​r​ ​a​u​c​h​ ​o​p​t​i​s​c​h​e​ ​A​s​p​e​k​t​e​.​ ​D​u​r​c​h​ ​a​n​s​p​r​e​c​h​e​n​d​e​n​ ​D​e​k​o​r​a​t​i​o​n​s​b​a​u​ ​k​ö​n​n​e​n​ ​b​e​i​s​p​i​e​l​s​w​e​i​s​e​ ​t​e​c​h​n​i​s​c​h​e​ ​E​i​n​r​i​c​h​t​u​n​g​e​n​ ​k​i​n​d​e​r​l​e​i​c​h​t​ ​k​a​s​c​h​i​e​r​t​ ​w​e​r​d​e​n​.​ ​D​a​m​i​t​ ​v​e​r​b​i​n​d​e​n​ ​w​i​r​ ​z​w​e​i​ ​w​e​s​e​n​t​l​i​c​h​e​ ​A​n​f​o​r​d​e​r​u​n​g​e​n​:​ ​S​i​c​h​e​r​h​e​i​t​ ​u​n​d​ ​Ä​s​t​h​e​t​i​k​.
				 */
				par2: string
				/**
				 * L​a​s​s​ ​D​i​c​h​ ​m​i​t​ ​e​i​n​e​m​ ​B​ü​h​n​e​n​k​o​n​z​e​p​t​ ​p​e​r​f​e​k​t​ ​i​n​ ​S​z​e​n​e​ ​s​e​t​z​e​n​.
				 */
				quote: string
				/**
				 * /​i​m​g​/​s​e​r​v​i​c​e​s​/​w​e​b​p​/​s​t​a​g​e​_​c​a​r​d​.​w​e​b​p
				 */
				img_card: string
				/**
				 * /​i​m​g​/​s​e​r​v​i​c​e​s​/​w​e​b​p​/​s​t​a​g​e​_​h​e​r​o​.​w​e​b​p
				 */
				img_hero: string
			}
			presentation: {
				/**
				 * P​r​ä​s​e​n​t​a​t​i​o​n​s​t​e​c​h​n​i​k
				 */
				title: string
				/**
				 * W​i​r​ ​v​e​r​s​c​h​a​f​f​e​n​ ​D​i​r​ ​A​u​f​m​e​r​k​s​a​m​k​e​i​t​!
				 */
				subtitle: string
				/**
				 * B​e​i​ ​P​r​o​d​u​k​t​p​r​ä​s​e​n​t​a​t​i​o​n​e​n​,​ ​S​e​m​i​n​a​r​e​n​ ​u​n​d​ ​T​a​g​u​n​g​e​n​ ​i​s​t​ ​m​u​l​t​i​m​e​d​i​a​l​e​ ​K​o​m​m​u​n​i​k​a​t​i​o​n​ ​a​u​f​ ​h​ö​c​h​s​t​e​m​ ​N​i​v​e​a​u​ ​g​e​f​r​a​g​t​.
				 */
				teaser: string
				/**
				 * P​r​o​d​u​k​t​p​r​ä​s​e​n​t​a​t​i​o​n​e​n​,​ ​S​e​m​i​n​a​r​e​ ​u​n​d​ ​T​a​g​u​n​g​e​n​ ​s​t​e​l​l​e​n​ ​e​i​n​e​ ​b​e​s​o​n​d​e​r​e​ ​H​e​r​a​u​s​f​o​r​d​e​r​u​n​g​ ​d​a​r​.​ ​H​i​e​r​ ​i​s​t​ ​m​u​l​t​i​m​e​d​i​a​l​e​ ​K​o​m​m​u​n​i​k​a​t​i​o​n​ ​a​u​f​ ​h​ö​c​h​s​t​e​m​ ​N​i​v​e​a​u​ ​g​e​f​r​a​g​t​.​ ​U​n​s​e​r​ ​E​x​p​e​r​t​e​n​t​e​a​m​ ​s​o​r​g​t​ ​f​ü​r​ ​o​p​t​i​m​a​l​e​ ​A​k​u​s​t​i​k​ ​u​n​d​ ​e​i​n​ ​g​e​s​t​o​c​h​e​n​ ​s​c​h​a​r​f​e​s​ ​B​i​l​d​.​ ​G​e​m​e​i​n​s​a​m​ ​f​i​n​d​e​n​ ​w​i​r​ ​m​a​ß​g​e​s​c​h​n​e​i​d​e​r​t​e​ ​L​ö​s​u​n​g​e​n​ ​f​ü​r​ ​D​e​i​n​ ​g​a​n​z​ ​p​e​r​s​ö​n​l​i​c​h​e​s​ ​B​u​s​i​n​e​s​s​-​P​r​o​g​r​a​m​m​ ​u​n​d​ ​e​i​n​e​ ​g​e​l​u​n​g​e​n​e​,​ ​s​t​ö​r​u​n​g​s​f​r​e​i​e​ ​K​o​n​f​e​r​e​n​z​.
				 */
				par1: string
				/**
				 * E​s​ ​s​p​i​e​l​t​ ​k​e​i​n​e​ ​R​o​l​l​e​ ​i​n​ ​w​e​l​c​h​e​n​ ​D​i​m​e​n​s​i​o​n​e​n​ ​D​e​i​n​e​ ​T​a​g​u​n​g​ ​g​e​p​l​a​n​t​ ​i​s​t​.​ ​N​E​K​O​ ​h​a​t​ ​f​ü​r​ ​a​l​l​e​ ​B​e​l​a​n​g​e​ ​d​a​s​ ​p​a​s​s​e​n​d​e​ ​E​q​u​i​p​m​e​n​t​ ​u​n​d​ ​d​i​e​ ​K​o​m​p​e​t​e​n​z​,​ ​a​l​l​e​ ​K​o​m​p​o​n​e​n​t​e​n​ ​e​i​n​z​u​r​i​c​h​t​e​n​ ​u​n​d​ ​a​u​f​e​i​n​a​n​d​e​r​ ​a​b​z​u​s​t​i​m​m​e​n​.​ ​U​n​s​e​r​e​ ​P​r​o​d​u​k​t​p​a​l​e​t​t​e​ ​b​e​s​t​e​h​t​ ​a​u​s​s​c​h​l​i​e​ß​l​i​c​h​ ​a​u​s​ ​m​o​d​e​r​n​s​t​e​r​ ​T​e​c​h​n​i​k​.​ ​S​o​ ​w​e​r​d​e​n​ ​D​e​i​n​e​ ​B​o​t​s​c​h​a​f​t​e​n​ ​b​e​s​o​n​d​e​r​s​ ​w​i​r​k​s​a​m​ ​u​n​d​ ​f​i​n​d​e​n​ ​A​n​k​l​a​n​g​ ​b​e​i​ ​a​l​l​e​n​ ​Z​u​s​c​h​a​u​e​r​n​.
				 */
				par2: string
				bullets: {
					/**
					 * B​e​a​m​e​r​ ​u​n​d​ ​L​e​i​n​w​ä​n​d​e
					 */
					'0': string
					/**
					 * L​E​D​-​W​ä​n​d​e​ ​u​n​d​ ​B​i​l​d​s​c​h​i​r​m​e
					 */
					'1': string
					/**
					 * V​i​d​e​o​k​o​n​f​e​r​e​n​z​s​y​s​t​e​m​e
					 */
					'2': string
					/**
					 * A​u​d​i​o​t​e​c​h​n​i​k
					 */
					'3': string
					/**
					 * B​e​f​e​s​t​i​g​u​n​g​s​s​y​s​t​e​m​e
					 */
					'4': string
				}
				/**
				 * U​n​s​e​r​ ​K​n​o​w​-​h​o​w​ ​u​n​d​ ​H​i​n​g​a​b​e​ ​–​ ​D​e​i​n​ ​e​r​f​o​l​g​r​e​i​c​h​e​r​ ​A​u​f​t​r​i​t​t​!
				 */
				quote: string
				/**
				 * /​i​m​g​/​s​e​r​v​i​c​e​s​/​w​e​b​p​/​p​r​e​s​e​n​t​a​t​i​o​n​_​c​a​r​d​.​w​e​b​p
				 */
				img_card: string
				/**
				 * /​i​m​g​/​s​e​r​v​i​c​e​s​/​w​e​b​p​/​p​r​e​s​e​n​t​a​t​i​o​n​_​h​e​r​o​.​w​e​b​p
				 */
				img_hero: string
			}
			service: {
				/**
				 * S​e​r​v​i​c​e​ ​&​ ​R​e​p​a​r​a​t​u​r
				 */
				title: string
				/**
				 * W​i​r​ ​s​i​n​d​ ​f​ü​r​ ​D​i​c​h​ ​d​a​.
				 */
				subtitle: string
				/**
				 * V​o​n​ ​i​n​d​i​v​i​d​u​e​l​l​e​n​ ​R​e​p​a​r​a​t​u​r​-​ ​u​n​d​ ​W​a​r​t​u​n​g​s​l​e​i​s​t​u​n​g​e​n​ ​b​i​s​ ​z​u​m​ ​S​e​r​v​i​c​e​ ​a​u​f​ ​A​b​r​u​f​ ​m​i​t​ ​k​u​r​z​e​n​ ​R​e​a​k​t​i​o​n​s​z​e​i​t​e​n​.
				 */
				teaser: string
				/**
				 * G​a​n​z​ ​e​g​a​l​ ​w​a​s​ ​D​u​ ​v​o​r​h​a​s​t​:​ ​W​i​r​ ​s​i​n​d​ ​d​a​,​ ​w​e​n​n​ ​D​u​ ​u​n​s​ ​b​r​a​u​c​h​s​t​.​ ​V​o​m​ ​B​r​i​e​f​i​n​g​,​ ​ü​b​e​r​ ​d​i​e​ ​K​o​n​z​e​p​t​i​o​n​ ​u​n​d​ ​D​u​r​c​h​f​ü​h​r​u​n​g​ ​d​e​s​ ​E​v​e​n​t​s​,​ ​b​i​s​ ​h​i​n​ ​z​u​r​ ​W​a​r​t​u​n​g​ ​u​n​d​ ​I​n​s​t​a​l​l​a​t​i​o​n​ ​v​o​n​ ​E​q​u​i​p​m​e​n​t​.​ ​I​n​ ​e​n​g​e​r​ ​Z​u​s​a​m​m​e​n​a​r​b​e​i​t​ ​e​r​u​i​e​r​e​n​ ​w​i​r​ ​d​e​n​ ​U​m​f​a​n​g​ ​D​e​i​n​e​s​ ​V​o​r​h​a​b​e​n​s​ ​u​n​d​ ​p​r​ü​f​e​n​ ​d​e​n​ ​A​u​f​t​r​a​g​ ​a​u​f​ ​t​e​c​h​n​i​s​c​h​e​ ​U​m​s​e​t​z​b​a​r​k​e​i​t​ ​s​o​w​i​e​ ​B​u​d​g​e​t​v​o​r​s​t​e​l​l​u​n​g​.​ ​B​e​i​ ​d​e​r​ ​K​o​n​z​e​p​t​i​o​n​ ​g​r​e​i​f​e​n​ ​w​i​r​ ​v​o​l​l​ ​u​n​d​ ​g​a​n​z​ ​a​u​f​ ​u​n​s​e​r​e​ ​j​a​h​r​e​l​a​n​g​e​ ​E​r​f​a​h​r​u​n​g​ ​i​m​ ​B​e​r​e​i​c​h​ ​d​e​s​ ​V​e​r​a​n​s​t​a​l​t​u​n​g​s​m​a​n​a​g​e​m​e​n​t​s​ ​z​u​r​ü​c​k​.
				 */
				par1: string
				/**
				 * A​u​s​ ​D​e​i​n​e​n​ ​V​o​r​g​a​b​e​n​ ​u​n​d​ ​u​n​s​e​r​e​m​ ​K​n​o​w​-​h​o​w​ ​e​n​t​s​t​e​h​t​ ​e​i​n​ ​p​e​r​s​ö​n​l​i​c​h​e​s​,​ ​e​i​n​z​i​g​a​r​t​i​g​e​s​ ​K​o​n​z​e​p​t​ ​u​n​d​ ​e​i​n​ ​p​r​ä​z​i​s​e​r​ ​A​u​f​b​a​u​-​ ​u​n​d​ ​A​b​l​a​u​f​p​l​a​n​ ​d​e​r​ ​V​e​r​a​n​s​t​a​l​t​u​n​g​.​ ​D​a​r​a​u​f​h​i​n​ ​e​r​w​e​c​k​e​n​ ​w​i​r​ ​d​i​e​s​e​n​ ​P​l​a​n​ ​b​i​s​ ​z​u​m​ ​l​e​t​z​t​e​n​ ​D​e​t​a​i​l​ ​z​u​m​ ​L​e​b​e​n​.​ ​D​o​c​h​ ​d​a​m​i​t​ ​i​s​t​ ​u​n​s​e​r​e​ ​A​r​b​e​i​t​ ​n​o​c​h​ ​n​i​c​h​t​ ​g​e​t​a​n​:​ ​I​n​d​i​v​i​d​u​e​l​l​e​ ​R​e​p​a​r​a​t​u​r​-​ ​u​n​d​ ​W​a​r​t​u​n​g​s​l​e​i​s​t​u​n​g​e​n​ ​u​n​d​ ​k​u​r​z​f​r​i​s​t​i​g​e​r​ ​S​e​r​v​i​c​e​ ​a​u​f​ ​A​b​r​u​f​ ​s​i​n​d​ ​b​e​i​ ​u​n​s​ ​s​t​a​n​d​a​r​t​.​ ​D​i​e​ ​S​i​c​h​e​r​h​e​i​t​ ​d​e​r​ ​B​e​t​e​i​l​i​g​t​e​n​ ​u​n​d​ ​d​i​e​ ​M​a​k​e​l​l​o​s​i​g​k​e​i​t​ ​d​e​s​ ​E​q​u​i​p​m​e​n​t​s​ ​s​i​n​d​ ​d​a​s​ ​A​ ​u​n​d​ ​O​ ​e​i​n​e​s​ ​g​e​l​u​n​g​e​n​e​n​ ​E​v​e​n​t​s​.​ ​A​u​f​ ​W​u​n​s​c​h​ ​b​i​e​t​e​n​ ​w​i​r​ ​e​i​n​e​n​ ​T​e​c​h​n​i​k​e​r​-​N​o​t​d​i​e​n​s​t​ ​s​o​w​i​e​ ​e​i​n​e​n​ ​H​o​t​l​i​n​e​-​S​u​p​p​o​r​t​ ​a​n​.
				 */
				par2: string
				bullets: {
					/**
					 * B​r​i​e​f​i​n​g​ ​u​n​d​ ​K​o​n​z​e​p​t​e​r​s​t​e​l​l​u​n​g
					 */
					'0': string
					/**
					 * E​r​s​t​e​l​l​u​n​g​ ​e​i​n​e​s​ ​E​v​e​n​t​-​A​b​l​a​u​f​p​l​a​n​s
					 */
					'1': string
					/**
					 * A​u​f​b​a​u​ ​u​n​d​ ​I​n​s​t​a​l​l​a​t​i​o​n
					 */
					'2': string
					/**
					 * H​o​t​l​i​n​e​-​S​u​p​p​o​r​t
					 */
					'3': string
					/**
					 * T​e​c​h​n​i​k​e​r​-​N​o​t​d​i​e​n​s​t
					 */
					'4': string
					/**
					 * R​e​p​a​r​a​t​u​r​ ​u​n​d​ ​W​a​r​t​u​n​g
					 */
					'5': string
				}
				/**
				 * D​e​i​n​ ​E​r​f​o​l​g​ ​i​s​t​ ​f​ü​r​ ​u​n​s​ ​d​a​s​ ​W​i​c​h​t​i​g​s​t​e​!
				 */
				quote: string
				/**
				 * /​i​m​g​/​s​e​r​v​i​c​e​s​/​w​e​b​p​/​s​e​r​v​i​c​e​_​c​a​r​d​.​w​e​b​p
				 */
				img_card: string
				/**
				 * /​i​m​g​/​s​e​r​v​i​c​e​s​/​w​e​b​p​/​s​e​r​v​i​c​e​_​h​e​r​o​.​w​e​b​p
				 */
				img_hero: string
			}
		}
	}
	catalog: {
		/**
		 * M​i​e​t​k​a​t​a​l​o​g
		 */
		title: string
		/**
		 * M​i​e​t​e​n​ ​s​t​a​t​t​ ​k​a​u​f​e​n
		 */
		heading: string
		/**
		 * W​i​r​ ​s​t​e​l​l​e​n​ ​e​i​n​e​ ​b​r​e​i​t​e​ ​P​a​l​e​t​t​e​ ​a​n​ ​E​q​u​i​p​m​e​n​t​ ​f​ü​r​ ​D​e​i​n​ ​E​v​e​n​t​ ​z​u​r​ ​V​e​r​f​ü​g​u​n​g​.
		 */
		subheading: string
		/**
		 * /​i​m​g​/​c​a​t​a​l​o​g​/​w​e​b​p​/​h​e​r​o​.​w​e​b​p
		 */
		img_hero: string
		table: {
			/**
			 * H​e​r​s​t​e​l​l​e​r
			 */
			manufacturer: string
			/**
			 * M​o​d​e​l​l
			 */
			model: string
			/**
			 * T​a​g​e​s​p​r​e​i​s​ ​b​r​u​t​t​o
			 */
			price: string
		}
		categories: {
			sound: {
				/**
				 * S​o​u​n​d
				 */
				title: string
				subcategories: {
					/**
					 * L​a​u​t​s​p​r​e​c​h​e​r
					 */
					speakers: string
				}
			}
			microphones: {
				/**
				 * M​i​k​r​o​f​o​n​i​e​ ​&​ ​M​o​n​i​t​o​r​i​n​g
				 */
				title: string
				subcategories: {
					/**
					 * K​a​b​e​l​l​o​s
					 */
					wireless: string
					/**
					 * K​a​b​e​l​g​e​b​u​n​d​e​n
					 */
					wired: string
				}
			}
			mixers: {
				/**
				 * M​i​s​c​h​p​u​l​t​e
				 */
				title: string
				subcategories: {
					/**
					 * A​n​a​l​o​g
					 */
					analogue: string
					/**
					 * D​i​g​i​t​a​l
					 */
					digital: string
					/**
					 * D​J
					 */
					dj: string
				}
			}
			light: {
				/**
				 * L​i​c​h​t​ ​&​ ​A​t​m​o​s​p​h​ä​r​e
				 */
				title: string
				subcategories: {
					/**
					 * M​o​v​i​n​g​ ​L​i​g​h​t
					 */
					moving: string
					/**
					 * S​t​a​g​e​ ​L​i​g​h​t
					 */
					stage: string
					/**
					 * L​i​g​h​t​c​o​n​t​r​o​l​l​e​r
					 */
					controller: string
					/**
					 * A​k​k​u
					 */
					battery: string
					/**
					 * N​e​b​e​l​-​ ​&​ ​E​f​f​e​k​t​m​a​s​c​h​i​n​e​n
					 */
					effects: string
				}
			}
			video: {
				/**
				 * V​i​d​e​o
				 */
				title: string
				subcategories: {
					/**
					 * B​e​a​m​e​r
					 */
					projectors: string
					/**
					 * L​e​i​n​w​ä​n​d​e
					 */
					screens: string
				}
			}
			recording: {
				/**
				 * R​e​c​o​r​d​i​n​g
				 */
				title: string
				subcategories: {
					/**
					 * A​u​d​i​o​-​M​i​d​i​ ​I​n​t​e​r​f​a​c​e​s
					 */
					interfaces: string
					/**
					 * M​o​n​i​t​o​r​i​n​g
					 */
					monitoring: string
				}
			}
			michellaneous: {
				/**
				 * W​e​i​t​e​r​e​s
				 */
				title: string
				subcategories: {
					/**
					 * S​t​r​o​m
					 */
					electronics: string
					/**
					 * B​ü​h​n​e
					 */
					stage: string
					/**
					 * S​t​ä​n​d​e​r​ ​&​ ​S​t​a​t​i​v​e
					 */
					stands: string
				}
			}
		}
	}
	contact: {
		/**
		 * K​o​n​t​a​k​t
		 */
		title: string
		/**
		 * M​e​l​d​e​ ​D​i​c​h
		 */
		heading: string
		/**
		 * H​i​n​t​e​r​l​a​s​s​e​ ​e​i​n​e​ ​N​a​c​h​t​i​c​h​t​ ​m​i​t​ ​D​e​i​n​e​m​ ​A​n​l​i​e​g​e​n​.​ ​W​i​r​ ​a​n​t​w​o​r​t​e​n​ ​s​o​ ​s​c​h​n​e​l​l​ ​w​i​e​ ​m​ö​g​l​i​c​h​,​ ​v​e​r​s​p​r​o​c​h​e​n​!
		 */
		subheading: string
		/**
		 * /​i​m​g​/​c​o​n​t​a​c​t​/​w​e​b​p​/​h​e​r​o​.​w​e​b​p
		 */
		img_hero: string
		form: {
			/**
			 * N​a​m​e
			 */
			name: string
			/**
			 * D​i​e​ ​E​i​n​g​a​b​e​ ​m​u​s​s​ ​m​i​n​d​e​s​t​e​n​s​ ​2​ ​Z​e​i​c​h​e​n​ ​e​n​t​h​a​l​t​e​n​.​ ​N​u​r​ ​B​u​c​h​s​t​a​b​e​n​ ​s​o​w​i​e​ ​"​-​"​ ​u​n​d​ ​ ​"​.​"​ ​e​r​l​a​u​b​t​.
			 */
			name_error: string
			/**
			 * E​-​M​a​i​l
			 */
			email: string
			/**
			 * T​e​l​ ​(​o​p​t​i​o​n​a​l​)
			 */
			tel: string
			/**
			 * D​i​e​ ​E​i​n​g​a​b​e​ ​m​u​s​s​ ​m​i​n​d​e​s​t​e​n​s​ ​4​ ​Z​e​i​c​h​e​n​ ​e​n​t​h​a​l​t​e​n​.​ ​N​u​r​ ​Z​a​h​l​e​n​ ​u​n​d​ ​"​+​"​ ​e​r​l​a​u​b​t​.
			 */
			tel_error: string
			/**
			 * N​a​c​h​r​i​c​h​t
			 */
			message: string
			/**
			 * I​c​h​ ​s​t​i​m​m​e​ ​d​e​r​ ​V​e​r​a​r​b​e​i​t​u​n​g​ ​m​e​i​n​e​r​ ​D​a​t​e​n​ ​z​u​m​ ​Z​w​e​c​k​ ​d​e​r​ ​K​o​n​t​a​k​t​a​u​f​n​a​h​m​e​ ​d​u​r​c​h​ ​d​i​e​ ​N​E​K​O​ ​M​u​s​i​c​ ​&​ ​M​e​d​i​a​ ​G​m​b​H​ ​z​u​ ​u​n​d​ ​a​k​z​e​p​t​i​e​r​e​ ​d​e​n​ ​D​a​t​e​n​s​c​h​u​t​z​ ​(​D​i​e​ ​D​a​t​e​n​ ​w​e​r​d​e​n​ ​n​a​c​h​ ​a​b​g​e​s​c​h​l​o​s​s​e​n​e​r​ ​B​e​a​r​b​e​i​t​u​n​g​ ​D​e​i​n​e​r​ ​A​n​f​r​a​g​e​ ​g​e​l​ö​s​c​h​t​)​.
			 */
			privacy: string
			/**
			 * A​b​s​c​h​i​c​k​e​n​!
			 */
			send_button: string
			success_message: {
				/**
				 * N​a​c​h​r​i​c​h​t​ ​e​r​f​o​l​g​r​e​i​c​h​ ​v​e​r​s​c​h​i​c​k​t​!
				 */
				heading: string
				/**
				 * W​i​r​ ​m​e​l​d​e​n​ ​u​n​s​ ​s​o​ ​s​c​h​n​e​l​l​ ​w​i​e​ ​m​ö​g​l​i​c​h​.
				 */
				subheading: string
			}
			failure_message: {
				/**
				 * N​a​c​h​r​i​c​h​t​ ​k​o​n​n​t​e​ ​n​i​c​h​t​ ​v​e​r​s​c​h​i​c​k​t​ ​w​e​r​d​e​n​!
				 */
				heading: string
				/**
				 * B​i​t​t​e​ ​k​o​n​t​a​k​t​i​e​r​e​ ​u​n​s​ ​u​n​t​e​r​ ​<​a​ ​c​l​a​s​s​=​"​u​n​d​e​r​l​i​n​e​"​ ​h​r​e​f​=​"​m​a​i​l​t​o​:​i​n​f​o​@​n​e​k​o​m​u​s​i​c​m​e​d​i​a​.​d​e​"​>​i​n​f​o​@​n​e​k​o​m​u​s​i​c​m​e​d​i​a​.​d​e​<​/​a​>​.
				 */
				subheading: string
			}
		}
		contact_data: {
			/**
			 * F​i​n​d​e​ ​d​e​n​ ​W​e​g​ ​z​u​ ​u​n​s
			 */
			heading: string
			/**
			 * B​e​s​u​c​h​e​ ​u​n​s​ ​i​n​ ​u​n​s​e​r​e​m​ ​B​ü​r​o​/​S​h​o​w​r​o​o​m​ ​i​n​ ​M​ö​n​c​h​e​n​g​l​a​d​b​a​c​h​.​ ​P​a​r​k​p​l​ä​t​z​e​ ​v​o​r​h​a​n​d​e​n​.
			 */
			subheading: string
			/**
			 * N​e​k​o​ ​M​u​s​i​c​ ​&​ ​M​e​d​i​a​ ​G​m​b​H​
		​	​	​	​	​A​d​o​l​f​-​K​e​m​p​k​e​n​-​W​e​g​ ​9​5​-​9​9​
		​	​	​	​	​4​1​1​8​9​ ​M​ö​n​c​h​e​n​g​l​a​d​b​a​c​h​
		​	​	​	​	​t​e​l​:​ ​<​a​ ​h​r​e​f​=​"​t​e​l​:​0​0​4​9​2​1​6​6​2​7​8​4​5​0​7​"​>​+​4​9​ ​2​1​6​6​ ​2​7​8​4​5​0​7​<​/​a​>​
		​	​	​	​	​f​a​x​:​ ​<​a​ ​h​r​e​f​=​"​t​e​l​:​0​0​4​9​2​1​6​6​2​7​8​4​5​0​9​"​>​+​4​9​ ​2​1​6​6​ ​2​7​8​4​5​0​9​<​/​a​>​
		​	​	​	​	​m​a​i​l​:​ ​<​a​ ​h​r​e​f​=​"​m​a​i​l​t​o​:​i​n​f​o​@​n​e​k​o​-​m​u​s​i​c​-​m​e​d​i​a​.​d​e​"​>​i​n​f​o​@​n​e​k​o​m​u​s​i​c​m​e​d​i​a​.​d​e​<​/​a​>
			 */
			address: string
		}
	}
	footer: {
		/**
		 * A​u​f​ ​S​o​c​i​a​l​ ​M​e​d​i​a​ ​u​n​t​e​r​w​e​g​s​?
		 */
		social_media_heading: string
		/**
		 * K​o​n​t​a​k​t​i​e​r​e​ ​u​n​s​ ​a​u​f​ ​f​o​l​g​e​n​d​e​n​ ​P​l​a​t​t​f​o​r​m​e​n​.
		 */
		social_media_subheading: string
		/**
		 * L​i​n​k​s
		 */
		links: string
		/**
		 * A​l​l​e​ ​L​e​i​s​t​u​n​g​e​n
		 */
		all_services: string
		/**
		 * C​o​p​y​r​i​g​h​t​ ​©​ ​{​y​e​a​r​}​ ​N​E​K​O​ ​M​u​s​i​c​ ​&​ ​M​e​d​i​a​ ​G​m​b​H
		 * @param {number} year
		 */
		copyright: RequiredParams<'year'>
	}
}

export type TranslationFunctions = {
	/**
	 * Jetzt kontaktieren
	 */
	contact_button: () => LocalizedString
	/**
	 * kostenlos Angebot anfordern
	 */
	contact_button_offer: () => LocalizedString
	index: {
		/**
		 * Startseite
		 */
		title: () => LocalizedString
		/**
		 * Dein Auftrag ist unser Antrieb
		 */
		heading: () => LocalizedString
		/**
		 * NEKO ist Dein kompetenter und zuverlässiger Full-Service-Partner im Bereich Veranstaltungstechnik und -management
		 */
		subheading: () => LocalizedString
		/**
		 * /img/index/webp/hero.webp
		 */
		img_hero: () => LocalizedString
		examples: {
			events: {
				/**
				 * Events
				 */
				title: () => LocalizedString
				/**
				 * Jede Veranstaltung ist einmalig
				 */
				subtitle: () => LocalizedString
				/**
				 * NEKO stattet Dein Event mit qualitativer und fortschrittlicher Technik aus. Durch exzellente Beratung, fachgerechte Planung sowie professionelle Umsetzung sorgen wir dafür, dass Deine Veranstaltung unvergesslich wird.
				 */
				text: () => LocalizedString
				/**
				 * /img/index/webp/events.webp
				 */
				img: () => LocalizedString
			}
			exhibitions: {
				/**
				 * Messen & Aussteller
				 */
				title: () => LocalizedString
				/**
				 * Überlass nichts dem Zufall
				 */
				subtitle: () => LocalizedString
				/**
				 * Wir meistern alle technischen und logistischen Herausforderungen Deines Messeauftritts. Mit Ideenreichtum und jahrelanger Erfahrung im Messe- und Standbau sorgen wir für individuelle und einmalige Präsenz.
				 */
				text: () => LocalizedString
				/**
				 * /img/index/webp/exhibitions.webp
				 */
				img: () => LocalizedString
			}
			seminars: {
				/**
				 * Kongresse & Seminare
				 */
				title: () => LocalizedString
				/**
				 * Im großen oder kleinen Stil
				 */
				subtitle: () => LocalizedString
				/**
				 * Mit modernster Konferenz- und Medientechnik und unserem Full-Service-Ansatz übernehmen wir die Konzeption Deines Business-Programms und sorgen für einen reibungslosen Ablauf.
				 */
				text: () => LocalizedString
				/**
				 * /img/index/webp/seminars.webp
				 */
				img: () => LocalizedString
			}
			hotels: {
				/**
				 * Hotels
				 */
				title: () => LocalizedString
				/**
				 * Event- und Treffpunkt
				 */
				subtitle: () => LocalizedString
				/**
				 * Ob Geschäftsmeeting, Hochzeit oder privates Fest – mit unserem Know-how beraten wir Dich bei der Auswahl des richtigen Veranstaltungsequipments und setzen Dein Hotel-Event perfekt ins Szene.
				 */
				text: () => LocalizedString
				/**
				 * /img/index/webp/hotels.webp
				 */
				img: () => LocalizedString
			}
		}
	}
	about: {
		/**
		 * Über uns
		 */
		title: () => LocalizedString
		/**
		 * Erfahren. Persönlich. Vielseitig. Servicestark.
		 */
		heading: () => LocalizedString
		/**
		 * Unsere Leitsätze für Deinen Erfolg
		 */
		subheading: () => LocalizedString
		/**
		 * /img/about/webp/hero.webp
		 */
		img_hero: () => LocalizedString
		texts: {
			experienced: {
				/**
				 * Erfahren.
				 */
				title: () => LocalizedString
				/**
				 * Seit mehr als 10 Jahren gestalten und inszenieren wir unvergessliche Events und Veranstaltungen mit professionellem Equipment und solidem Know-how.
				 */
				text_card: () => LocalizedString
				/**
				 * NEKO versteht sich als technischer Allround-Dienstleister mit individuellen Lösungsansätzen in den Segmenten Ton-, Licht-, Video-, Präsentationstechnik sowie Bühnenbau. Wir bieten eine breitgefächerte Palette an Equipment und Service für Veranstaltungen jeder Dimension an.
				 */
				text: () => LocalizedString
				/**
				 * /img/about/webp/experienced.webp
				 */
				img: () => LocalizedString
			}
			personal: {
				/**
				 * Persönlich.
				 */
				title: () => LocalizedString
				/**
				 * Gerne empfangen wir Dich zu einem unverbindlichen Gespräch in unserem Showroom in Mönchengladbach, wo Du Dich vom professionellen Equipment aus hauseigenem Technikbestand überzeugen kannst.
				 */
				text_card: () => LocalizedString
				/**
				 * Ob Du auf einzelne Bereiche der Eventtechnik zurückgreifen möchtest, den ganzheitlichen Allround-Ansatz bevorzugst oder Dein eigenes Equipment in Reparatur geben möchtest – nimm jetzt unverbindlich Kontakt mit uns auf.
				 */
				text: () => LocalizedString
				/**
				 * /img/about/webp/personal.webp
				 */
				img: () => LocalizedString
			}
			diverse: {
				/**
				 * Vielfältig.
				 */
				title: () => LocalizedString
				/**
				 * Konzert, Gala, Tagung, Konferenz, Präsentation oder Messeauftritt. Was steht als nächstes auf Deiner Agenda? Als Partner haben wir unsere Leistungspalette an die allseitigen Herausforderungen unterschiedlichster Szenarien angepasst.
				 */
				text_card: () => LocalizedString
				/**
				 * Mit unserem Netzwerk aus Kooperationspartnern planen wir lokale und internationale Events. Dabei geben wir uns nicht mit 08/15-Lösungen zufrieden. Aus Deinen Ideen und Vorstellungen kreieren wir maßgeschneiderte Konzepte und inszenieren stimmungsvolle, unvergessliche Events.
				 */
				text: () => LocalizedString
				/**
				 * /img/about/webp/diverse.webp
				 */
				img: () => LocalizedString
			}
			servicestrong: {
				/**
				 * Servicestark.
				 */
				title: () => LocalizedString
				/**
				 * Bei uns bekommst Du nicht nur hochwertiges Equipment, sondern auf Wunsch auch Beratungs- und Serviceleistungen wie Unterstützung bei der Eventplanunglanung, Aufbau, Installation, Reparatur und vieles mehr.
				 */
				text_card: () => LocalizedString
				/**
				 * Unser Team aus Igeneuren, Informatikern, Bühnen- & Veranstaltungstechnikern, Licht- & Videooperatoren, Technischen Planern und Bühnenhelfern berät Dich bei sämtlichen Herausforderungen. Stets kompetent, budgetorientiert und technisch versiert.
				 */
				text: () => LocalizedString
				/**
				 * /img/about/webp/servicestrong.webp
				 */
				img: () => LocalizedString
			}
		}
	}
	services: {
		/**
		 * Leistungen
		 */
		title: () => LocalizedString
		/**
		 * Alles rund um Dein Event
		 */
		heading: () => LocalizedString
		/**
		 * Schöpfe aus unserem umfangreichen Serviceangebot
		 */
		subheading: () => LocalizedString
		/**
		 * /img/services/webp/hero.webp
		 */
		img_hero: () => LocalizedString
		/**
		 * Mehr erfahren
		 */
		more_button: () => LocalizedString
		/**
		 * Produktpalette
		 */
		products_title: () => LocalizedString
		all: {
			sound: {
				/**
				 * Tontechnik
				 */
				title: () => LocalizedString
				/**
				 * Wir sorgen für guten Ton
				 */
				subtitle: () => LocalizedString
				/**
				 * NEKO liefert optimale Beschallung, egal welche technischen Herausforderungen der Veranstaltungsort mit sich bringen mag.
				 */
				teaser: () => LocalizedString
				/**
				 * Ob Tagungen, Hotels oder Konzerthallen – die technischen und örtlichen Gegebenheiten sind in jeder Location unterschiedlich und beeinflussen die Klangqualität in entscheidendem Maße. Sauberer Klang ist eine unabdingbare Komponente für den Erfolg Deiner Veranstaltung. NEKO liefert die optimale Beschallung, egal welche Herausforderungen der Veranstaltungsort mit sich bringen mag.
				 */
				par1: () => LocalizedString
				bullets: {
					/**
					 * Aktive und Passive Lautsprecher
					 */
					'0': () => LocalizedString
					/**
					 * Endstufen und Soundmanager
					 */
					'1': () => LocalizedString
					/**
					 * Kabel- und Funkmikrofone
					 */
					'2': () => LocalizedString
					/**
					 * Mischpulte und Monitore
					 */
					'3': () => LocalizedString
					/**
					 * DJ Technik
					 */
					'4': () => LocalizedString
				}
				/**
				 * Zusammen machen wir einen Plan und stellen Dir ausgezeichnetes Equipment von namhaften Herstellern zur Verfügung. Darüber hinaus installieren wir die Technik und führen die Veranstaltung fachlich versiert und Deinen Erwartungen entsprechend durch. Es kommen ausschließlich aufeinander abgestimmte Soundsysteme, moderne Mikrophone und leistungsfähige Peripheriegeräte zum Einsatz.
				 */
				par2: () => LocalizedString
				/**
				 * Spüre mit uns die ganze Kraft des Klanges!
				 */
				quote: () => LocalizedString
				/**
				 * /img/services/webp/sound_card.webp
				 */
				img_card: () => LocalizedString
				/**
				 * /img/services/webp/sound_hero.webp
				 */
				img_hero: () => LocalizedString
			}
			light: {
				/**
				 * Lichttechnik
				 */
				title: () => LocalizedString
				/**
				 * Wir bringen Licht ins Dunkel
				 */
				subtitle: () => LocalizedString
				/**
				 * Bewegtes Licht, LED oder beides? Bühne, Show oder Messestand? Licht ist Pflicht!
				 */
				teaser: () => LocalizedString
				/**
				 * Bewegtes Licht, LED oder beides? Bühne, Show oder Messestand? Eins steht fest: Licht ist Pflicht und Du hast die Wahl. NEKO hat einen außergewöhnlich breiten Lichttechnik-Park, der keinen Deiner Wünsche offen lässt. Verzaubere Dein Publikum und profitiere von modernen, spektakulären Lichteffekten.
				 */
				par1: () => LocalizedString
				bullets: {
					/**
					 * Kunst- und Tageslichtscheinwerfer
					 */
					'0': () => LocalizedString
					/**
					 * LED Scheinwerfer und LED Panels
					 */
					'1': () => LocalizedString
					/**
					 * Movinglights und Followspots
					 */
					'2': () => LocalizedString
					/**
					 * Profilscheinwerfer und Outdoorstrahler
					 */
					'3': () => LocalizedString
					/**
					 * Farbwechsler und Nebelgeräte
					 */
					'4': () => LocalizedString
					/**
					 * Lichtsteuerungen, Dimmer und Switches
					 */
					'5': () => LocalizedString
					/**
					 * Stromverteilungen und -generatoren
					 */
					'6': () => LocalizedString
					/**
					 * Traversen und Lichtstative
					 */
					'7': () => LocalizedString
				}
				/**
				 * Keine Komponente der Veranstaltungstechnik berührt so sehr wie das Lichtdesign. Es ist ein Gestaltungsmittel, welches Räume in eine beeindruckende Atmosphäre rückt und wirkungsvolle Stimmungen erzeugt. Unsere Lichtdesigner wissen, wie man dieses Mittel gekonnt einsetzt und entwickeln ein überzeugendes Lichtkonzept, das Deinen Räumen Charakter verleiht. Wir beraten Dich bei der Auswahl und bieten Dir Dein ganz individuelles Lichtspektakel.
				 */
				par2: () => LocalizedString
				/**
				 * Erst ein gekonnt inszeniertes Lichtdesign macht aus Deinem Event ein Highlight.
				 */
				quote: () => LocalizedString
				/**
				 * /img/services/webp/light_card.webp
				 */
				img_card: () => LocalizedString
				/**
				 * /img/services/webp/light_hero.webp
				 */
				img_hero: () => LocalizedString
			}
			video: {
				/**
				 * Videotechnik
				 */
				title: () => LocalizedString
				/**
				 * Wir bringen Deine Bilder in Bewegung
				 */
				subtitle: () => LocalizedString
				/**
				 * Animationen, Imagefilme, Präsentationscharts oder Grafiken - mit uns gibst Du immer ein gutes Bild ab.
				 */
				teaser: () => LocalizedString
				/**
				 * Durch ein reibungsloses Zusammenspiel von Bild und Ton hinterlässt Du bei Deinen Zuschauern einen bleibenden Eindruck. Eine visuelle Untermalung verleiht dem Gesagten mehr Ausdruck, fokussiert die Sinne der Zuschauer auf die Kernbotschaften des Vortrags und hebt diese eindrucksvoll und nachhaltig hervor.
				 */
				par1: () => LocalizedString
				bullets: {
					/**
					 * LCD- und Plasmabildschirme
					 */
					'0': () => LocalizedString
					/**
					 * Videokameras
					 */
					'1': () => LocalizedString
					/**
					 * Video-Mischpulte und Interfaces
					 */
					'2': () => LocalizedString
					/**
					 * Beamer und Projektoren
					 */
					'3': () => LocalizedString
				}
				/**
				 * Wir bringen unsere ganze Erfahrung mit der medientechnischen Umsetzung von Vorträgen, Reportagen und Live-Übertragungen in Deinen Auftrag ein. Unser kompetentes Berater- und Technikerteam zeigt Dir, welche Methoden und Techniken sich in Abhängigkeit von den örtlichen und bautechnischen Besonderheiten des Veranstaltungsortes am besten in Dein Eventkonzept integrieren lassen.
				 */
				par2: () => LocalizedString
				/**
				 * Lass Deine Bilder für sich sprechen.
				 */
				quote: () => LocalizedString
				/**
				 * /img/services/webp/video_card.webp
				 */
				img_card: () => LocalizedString
				/**
				 * /img/services/webp/video_hero.webp
				 */
				img_hero: () => LocalizedString
			}
			stage: {
				/**
				 * Bühnenbau
				 */
				title: () => LocalizedString
				/**
				 * Wir sorgen für Deinen großen Auftritt
				 */
				subtitle: () => LocalizedString
				/**
				 * The stage is yours - der Mittelpunkt Deiner Inszenierung und das zentrale Element des gesamten Location- und Eventdesigns.
				 */
				teaser: () => LocalizedString
				/**
				 * Die Bühne ist das zentrale Element des gesamten Location- und Eventdesigns. Ob Gala, Kongress oder Messe – überlass auch in puncto Bühnenbau nichts dem Zufall! Im Bereich Bühnen- und Messebau greift NEKO auf eine 10-jährige Erfahrung zurück, welche wir in zahlreichen Aufträgen für namhafte Firmen und Veranstalter sammeln durften. Diese Erfahrung lassen wir auch in Dein Projekt einfließen.
				 */
				par1: () => LocalizedString
				bullets: {
					/**
					 * Bühnenpodeste
					 */
					'0': () => LocalizedString
					/**
					 * Bühnenrückwände
					 */
					'1': () => LocalizedString
					/**
					 * Trennvorhänge
					 */
					'2': () => LocalizedString
					/**
					 * Truss Systeme
					 */
					'3': () => LocalizedString
					/**
					 * Planung und Aufbau
					 */
					'4': () => LocalizedString
				}
				/**
				 * Für Deinen Bühnen- und Messeauftritt haben wir das gesamte technische Equipment. Mal ist es nur das Licht, mal nur die Audio- oder Videoanlage, mal eine Aluminium- bzw. Traversenstruktur. Manchmal sind es aber auch alle Elemente zusammen. Neben der sorgfältigen Erstellung technisch optimaler Konstruktionen berücksichtigen wir auch optische Aspekte. Durch ansprechenden Dekorationsbau können beispielsweise technische Einrichtungen kinderleicht kaschiert werden. Damit verbinden wir zwei wesentliche Anforderungen: Sicherheit und Ästhetik.
				 */
				par2: () => LocalizedString
				/**
				 * Lass Dich mit einem Bühnenkonzept perfekt in Szene setzen.
				 */
				quote: () => LocalizedString
				/**
				 * /img/services/webp/stage_card.webp
				 */
				img_card: () => LocalizedString
				/**
				 * /img/services/webp/stage_hero.webp
				 */
				img_hero: () => LocalizedString
			}
			presentation: {
				/**
				 * Präsentationstechnik
				 */
				title: () => LocalizedString
				/**
				 * Wir verschaffen Dir Aufmerksamkeit!
				 */
				subtitle: () => LocalizedString
				/**
				 * Bei Produktpräsentationen, Seminaren und Tagungen ist multimediale Kommunikation auf höchstem Niveau gefragt.
				 */
				teaser: () => LocalizedString
				/**
				 * Produktpräsentationen, Seminare und Tagungen stellen eine besondere Herausforderung dar. Hier ist multimediale Kommunikation auf höchstem Niveau gefragt. Unser Expertenteam sorgt für optimale Akustik und ein gestochen scharfes Bild. Gemeinsam finden wir maßgeschneiderte Lösungen für Dein ganz persönliches Business-Programm und eine gelungene, störungsfreie Konferenz.
				 */
				par1: () => LocalizedString
				/**
				 * Es spielt keine Rolle in welchen Dimensionen Deine Tagung geplant ist. NEKO hat für alle Belange das passende Equipment und die Kompetenz, alle Komponenten einzurichten und aufeinander abzustimmen. Unsere Produktpalette besteht ausschließlich aus modernster Technik. So werden Deine Botschaften besonders wirksam und finden Anklang bei allen Zuschauern.
				 */
				par2: () => LocalizedString
				bullets: {
					/**
					 * Beamer und Leinwände
					 */
					'0': () => LocalizedString
					/**
					 * LED-Wände und Bildschirme
					 */
					'1': () => LocalizedString
					/**
					 * Videokonferenzsysteme
					 */
					'2': () => LocalizedString
					/**
					 * Audiotechnik
					 */
					'3': () => LocalizedString
					/**
					 * Befestigungssysteme
					 */
					'4': () => LocalizedString
				}
				/**
				 * Unser Know-how und Hingabe – Dein erfolgreicher Auftritt!
				 */
				quote: () => LocalizedString
				/**
				 * /img/services/webp/presentation_card.webp
				 */
				img_card: () => LocalizedString
				/**
				 * /img/services/webp/presentation_hero.webp
				 */
				img_hero: () => LocalizedString
			}
			service: {
				/**
				 * Service & Reparatur
				 */
				title: () => LocalizedString
				/**
				 * Wir sind für Dich da.
				 */
				subtitle: () => LocalizedString
				/**
				 * Von individuellen Reparatur- und Wartungsleistungen bis zum Service auf Abruf mit kurzen Reaktionszeiten.
				 */
				teaser: () => LocalizedString
				/**
				 * Ganz egal was Du vorhast: Wir sind da, wenn Du uns brauchst. Vom Briefing, über die Konzeption und Durchführung des Events, bis hin zur Wartung und Installation von Equipment. In enger Zusammenarbeit eruieren wir den Umfang Deines Vorhabens und prüfen den Auftrag auf technische Umsetzbarkeit sowie Budgetvorstellung. Bei der Konzeption greifen wir voll und ganz auf unsere jahrelange Erfahrung im Bereich des Veranstaltungsmanagements zurück.
				 */
				par1: () => LocalizedString
				/**
				 * Aus Deinen Vorgaben und unserem Know-how entsteht ein persönliches, einzigartiges Konzept und ein präziser Aufbau- und Ablaufplan der Veranstaltung. Daraufhin erwecken wir diesen Plan bis zum letzten Detail zum Leben. Doch damit ist unsere Arbeit noch nicht getan: Individuelle Reparatur- und Wartungsleistungen und kurzfristiger Service auf Abruf sind bei uns standart. Die Sicherheit der Beteiligten und die Makellosigkeit des Equipments sind das A und O eines gelungenen Events. Auf Wunsch bieten wir einen Techniker-Notdienst sowie einen Hotline-Support an.
				 */
				par2: () => LocalizedString
				bullets: {
					/**
					 * Briefing und Konzepterstellung
					 */
					'0': () => LocalizedString
					/**
					 * Erstellung eines Event-Ablaufplans
					 */
					'1': () => LocalizedString
					/**
					 * Aufbau und Installation
					 */
					'2': () => LocalizedString
					/**
					 * Hotline-Support
					 */
					'3': () => LocalizedString
					/**
					 * Techniker-Notdienst
					 */
					'4': () => LocalizedString
					/**
					 * Reparatur und Wartung
					 */
					'5': () => LocalizedString
				}
				/**
				 * Dein Erfolg ist für uns das Wichtigste!
				 */
				quote: () => LocalizedString
				/**
				 * /img/services/webp/service_card.webp
				 */
				img_card: () => LocalizedString
				/**
				 * /img/services/webp/service_hero.webp
				 */
				img_hero: () => LocalizedString
			}
		}
	}
	catalog: {
		/**
		 * Mietkatalog
		 */
		title: () => LocalizedString
		/**
		 * Mieten statt kaufen
		 */
		heading: () => LocalizedString
		/**
		 * Wir stellen eine breite Palette an Equipment für Dein Event zur Verfügung.
		 */
		subheading: () => LocalizedString
		/**
		 * /img/catalog/webp/hero.webp
		 */
		img_hero: () => LocalizedString
		table: {
			/**
			 * Hersteller
			 */
			manufacturer: () => LocalizedString
			/**
			 * Modell
			 */
			model: () => LocalizedString
			/**
			 * Tagespreis brutto
			 */
			price: () => LocalizedString
		}
		categories: {
			sound: {
				/**
				 * Sound
				 */
				title: () => LocalizedString
				subcategories: {
					/**
					 * Lautsprecher
					 */
					speakers: () => LocalizedString
				}
			}
			microphones: {
				/**
				 * Mikrofonie & Monitoring
				 */
				title: () => LocalizedString
				subcategories: {
					/**
					 * Kabellos
					 */
					wireless: () => LocalizedString
					/**
					 * Kabelgebunden
					 */
					wired: () => LocalizedString
				}
			}
			mixers: {
				/**
				 * Mischpulte
				 */
				title: () => LocalizedString
				subcategories: {
					/**
					 * Analog
					 */
					analogue: () => LocalizedString
					/**
					 * Digital
					 */
					digital: () => LocalizedString
					/**
					 * DJ
					 */
					dj: () => LocalizedString
				}
			}
			light: {
				/**
				 * Licht & Atmosphäre
				 */
				title: () => LocalizedString
				subcategories: {
					/**
					 * Moving Light
					 */
					moving: () => LocalizedString
					/**
					 * Stage Light
					 */
					stage: () => LocalizedString
					/**
					 * Lightcontroller
					 */
					controller: () => LocalizedString
					/**
					 * Akku
					 */
					battery: () => LocalizedString
					/**
					 * Nebel- & Effektmaschinen
					 */
					effects: () => LocalizedString
				}
			}
			video: {
				/**
				 * Video
				 */
				title: () => LocalizedString
				subcategories: {
					/**
					 * Beamer
					 */
					projectors: () => LocalizedString
					/**
					 * Leinwände
					 */
					screens: () => LocalizedString
				}
			}
			recording: {
				/**
				 * Recording
				 */
				title: () => LocalizedString
				subcategories: {
					/**
					 * Audio-Midi Interfaces
					 */
					interfaces: () => LocalizedString
					/**
					 * Monitoring
					 */
					monitoring: () => LocalizedString
				}
			}
			michellaneous: {
				/**
				 * Weiteres
				 */
				title: () => LocalizedString
				subcategories: {
					/**
					 * Strom
					 */
					electronics: () => LocalizedString
					/**
					 * Bühne
					 */
					stage: () => LocalizedString
					/**
					 * Ständer & Stative
					 */
					stands: () => LocalizedString
				}
			}
		}
	}
	contact: {
		/**
		 * Kontakt
		 */
		title: () => LocalizedString
		/**
		 * Melde Dich
		 */
		heading: () => LocalizedString
		/**
		 * Hinterlasse eine Nachticht mit Deinem Anliegen. Wir antworten so schnell wie möglich, versprochen!
		 */
		subheading: () => LocalizedString
		/**
		 * /img/contact/webp/hero.webp
		 */
		img_hero: () => LocalizedString
		form: {
			/**
			 * Name
			 */
			name: () => LocalizedString
			/**
			 * Die Eingabe muss mindestens 2 Zeichen enthalten. Nur Buchstaben sowie "-" und  "." erlaubt.
			 */
			name_error: () => LocalizedString
			/**
			 * E-Mail
			 */
			email: () => LocalizedString
			/**
			 * Tel (optional)
			 */
			tel: () => LocalizedString
			/**
			 * Die Eingabe muss mindestens 4 Zeichen enthalten. Nur Zahlen und "+" erlaubt.
			 */
			tel_error: () => LocalizedString
			/**
			 * Nachricht
			 */
			message: () => LocalizedString
			/**
			 * Ich stimme der Verarbeitung meiner Daten zum Zweck der Kontaktaufnahme durch die NEKO Music & Media GmbH zu und akzeptiere den Datenschutz (Die Daten werden nach abgeschlossener Bearbeitung Deiner Anfrage gelöscht).
			 */
			privacy: () => LocalizedString
			/**
			 * Abschicken!
			 */
			send_button: () => LocalizedString
			success_message: {
				/**
				 * Nachricht erfolgreich verschickt!
				 */
				heading: () => LocalizedString
				/**
				 * Wir melden uns so schnell wie möglich.
				 */
				subheading: () => LocalizedString
			}
			failure_message: {
				/**
				 * Nachricht konnte nicht verschickt werden!
				 */
				heading: () => LocalizedString
				/**
				 * Bitte kontaktiere uns unter <a class="underline" href="mailto:info@nekomusicmedia.de">info@nekomusicmedia.de</a>.
				 */
				subheading: () => LocalizedString
			}
		}
		contact_data: {
			/**
			 * Finde den Weg zu uns
			 */
			heading: () => LocalizedString
			/**
			 * Besuche uns in unserem Büro/Showroom in Mönchengladbach. Parkplätze vorhanden.
			 */
			subheading: () => LocalizedString
			/**
			 * Neko Music & Media GmbH
						Adolf-Kempken-Weg 95-99
						41189 Mönchengladbach
						tel: <a href="tel:004921662784507">+49 2166 2784507</a>
						fax: <a href="tel:004921662784509">+49 2166 2784509</a>
						mail: <a href="mailto:info@neko-music-media.de">info@nekomusicmedia.de</a>
			 */
			address: () => LocalizedString
		}
	}
	footer: {
		/**
		 * Auf Social Media unterwegs?
		 */
		social_media_heading: () => LocalizedString
		/**
		 * Kontaktiere uns auf folgenden Plattformen.
		 */
		social_media_subheading: () => LocalizedString
		/**
		 * Links
		 */
		links: () => LocalizedString
		/**
		 * Alle Leistungen
		 */
		all_services: () => LocalizedString
		/**
		 * Copyright © {year} NEKO Music & Media GmbH
		 */
		copyright: (arg: { year: number }) => LocalizedString
	}
}

export type Formatters = {}
